services:
  mysql:
    image: mysql:8.0
    container_name: quickqueue_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: quickqueue_db
      MYSQL_USER: quickqueue_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - quickqueue_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./quickqueue
      dockerfile: Dockerfile
    container_name: quickqueue_backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - quickqueue_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql:3306/quickqueue_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATASORUCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASORUCE_PASSWORD: ${MYSQL_PASSWORD}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      SOLAPI_API_KEY: ${SOLAPI_API_KEY}
      SOLAPI_API_SECRET: ${SOLAPI_API_SECRET}
      SOLAPI_SENDER: ${SOLAPI_SENDER}
  
  frontend:
    build:
      context: ./quickqueue_front
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: quickqueue_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - quickqueue_network
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}

networks:
  quickqueue_network:
    driver: bridge

volumes:
  mysql_data: